config/routes.rb
Rails.application.routes.draw do

  root 'games#index'
  resources :players
  resources :sessions
  resources :games do
    member do
      post 'join'
      post 'match'
      post 'submit'
      post 'forfeit'
    end
  end

end

app/views/shared/_game_status.html.erb
<div class="game_status">
  <% if @game %>
    <div class="game_info">
        <div>
            Game Number <%= @game.id %>
        </div>
        <% if @game.status == "active" %>
            Tiles Remaining: <%= @game.tiles_remaining %>
            <%= @game.current_player.username.capitalize %>'s turn
        <% end %>
    </div>
  <div class="scores">
    <% if @game.status == "active" %>
        <%= render partial: 'shared/scores' %>
    <% else %>
        Waiting for Opponent
    <% end %>
  </div>
    <%= button_to "Forfeit", forfeit_game_path, class: "button logout_button", :confirm => "Are you sure you want to forfeit?" %>
  <% end %>
  <%= button_to "Log Out", session_path(session[:id]), class: "button logout_button", method: :delete, :confirm => "Are you sure you want to log out?" %>
</div>

app/views/shared/_letter.html.erb
<div class="letter">
  <div class="title-letter"><p><%= letter %></p></div>
  <% if tile = Tile.find_by_letter(letter.upcase) %>
    <% value = tile.value %>
  <% else %>
    <% value = "?" %>
  <% end %>
  <div class="title-value"><%= value %></div>
</div>

app/views/shared/_login.html.erb
<div class="login">
    <%= form_tag('/sessions', method: "post") do %>
        <div>
          <%= label_tag "Username:" %>
          <%= text_field_tag :username, nil, class: "field" %>
        </div>
        <div>
          <%= label_tag "Password:" %>
          <%= password_field_tag :password, nil, class: "field" %>
        </div>
        <div>
          <%= submit_tag "Sign In", class: "button signin_button" %>
        </div>
    <% end %>
</div>

app/views/shared/_navbar.html.erb
<div id="header">
  <div class="header_title">
    <%= link_to "Scrabbulous", root_path %>
  </div>
  <div class="header_links">
    <% if session[:id] %>
      <%= link_to "logout", session_path(session[:id]), method: :delete %>
      <%= link_to "profile", games_path %>
    <% else %>
      <%= link_to "signup", new_player_path %>
      <%= link_to "signin", new_session_path %>
    <% end %>
  </div>
 </div> 

app/views/shared/_scores.html.erb
  <div>
    <%= link_to @game.players.first.username.capitalize, player_path(@game.players.first) %>
    : <%= @game.playergames.first.score %>
  </div>
  <div>
    <%= link_to @game.players.last.username.capitalize, player_path(@game.players.last) %>
    : <%= @game.playergames.last.score %>
  </div>

app/views/shared/_sidebar.html.erb
<div id="sidebar">
  <div id="sidebar_top">
      <% if session[:id] %>
        <%= link_to (render partial: 'shared/word_vertical', locals: {word: Player.find(session[:id]).username }), player_path(session[:id]) %>
        <%= render partial: 'shared/game_status' %>

      <% else %>
        <%= render partial: 'shared/word_vertical', locals: { word: "scrabbble" }%>
      <% end %>
  </div>
  <div class="scrabble">
    <% if session[:id] %>
        <%= link_to "Scrabbble", root_path %>
    <% end %>
  </div>
</div>

app/views/shared/_tray.html.erb
<div class="submit_button">
      <%= button_to "Submit", submit_game_path, disabled: !(@game.current_player_id == @player.id), :id => "submit_turn", :class => "button", data: {disable_with: "Submitting..."} %>
</div>
  <div class="tray">
    <table id="tray">
      <tr>
        <% (0..6).each do |tile_index| %>
            <td class="tray_cell">
              <% if @playertiles.length > tile_index %>
                <%= render partial: 'tile', locals: {letter: @playertiles[tile_index].tile.letter, value: @playertiles[tile_index].tile.value, active: true} %>
              <% end %>
            </td>
        <% end %>
      </tr>
    </table>
  </div>
  <div class="tray_buttons">
    <div><%= button_to "Shuffle", {}, :class => "button", :id => "shuffle" %></div>
    <div><%= button_to "Reset Letters", {}, :class => "button", :id => "reset" %></div>
  </div>
</div>

app/views/shared/_traybar.html.erb
<div class="tray_area">
  <% if session[:id] %>
      <% if @game && @game.players.include?(Player.find(session[:id])) %>
          <%= render partial: 'shared/tray' %>

      <% else %>
          <%= button_to "Create Game", games_path, :class => "button create_game_button", :method => :post%>
      <% end %>
  <% else %>
      <%= render partial: 'shared/login' %>
  <% end %>
</div>

app/views/shared/_welcome.html.erb
<div class="welcome">

    <h1 class="welcome-title">Scrabbble</h1>
    <div class="welcome-motto">
        <h2>Where Q's and Z's are worth 9</h2>
        <h4 id="game_logic">And everyday is game logic day</h4>
    </div>

    Not already a player?
    <%= link_to "Sign Up", new_player_path, class: "button signup_button"%>
</div>

app/views/shared/_word_vertical.html.erb
<div class="vertical_word">
    <% upcase_nine_letters(word).each do |letter| %>
        <%= render partial: 'shared/letter', locals: {letter: letter}%>
    <% end %>
</div>