config/routes.rb
Rails.application.routes.draw do

  root 'games#index'
  resources :players
  resources :sessions
  resources :games do
    member do
      post 'join'
      post 'match'
      post 'submit'
      post 'forfeit'
    end
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :playergames
  has_many :players, through: :playergames
  has_many :gametiles
  belongs_to :winner, class_name: 'Player'
  belongs_to :current_player, class_name: 'Player'

  before_create {self.status = 'pending'}

  def self.pending
    Game.all.select{ |game| game.status == 'pending' }
  end

  def self.dimension
    15
  end

  def self.calculate_score(words)
    letters = words.gsub(/-/, '').split('')
    score = 0
    letters.each do |letter|
      score += Tile.where(letter: letter).first.value
    end
    score
  end

  def tiles_remaining
    Gametile.where(playergame_id: nil, cell_id: nil, game: self.id).count
  end

  def find_cell_letter(x, y)
    cell = Cell.where(:x_coord => x, :y_coord => y).first
    game_tile = Gametile.where(game: self, cell: cell).first
    game_tile ? game_tile.tile.letter : nil
  end

  def change_turn
    if self.current_player_id == self.players.first.id
      self.current_player_id = self.players.last.id
    else
      self.current_player_id = self.players.first.id
    end
    self.save
  end

  def start
    self.status = 'active'
    self.current_player_id = self.players.first.id
    self.players.each do |player|
      game_tiles = Gametile.where(playergame_id: nil, cell_id: nil, game: self.id).sample(7)
      player_game = Playergame.where(game: self.id, player: player).first
      game_tiles.each do |game_tile|
        game_tile.playergame_id = player_game.id
        game_tile.save
      end
    end
    self.save
  end

  def complete
    self.status = 'completed'
  end

  def put_tiles_on_board_and_change_turn(input_tiles, game_tiles)
    input_tiles.each do |tile|
      game_tiles.each do |gametile|
        if gametile.tile.letter == tile[:letter]
          @game_tile = gametile
        end
      end
      @game_tile.put_on_board(Cell.where(x_coord: tile[:x], y_coord: tile[:y]).first)
    end
    self.change_turn
  end
end

app/models/games.rb
class Games < ActiveRecord::Base
  has_many :playergames
  has_many :gametiles
  has_many :cells
  belongs_to :winner, class_name: "Player"
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.pending
    @player = Player.find(session[:id]) if session[:id]
  end

  def create
    @game = Game.create
    Playergame.create(game: @game, player_id: session[:id], score: 0)
    @tiles = Tile.all
    @tiles.each do |tile|
      Gametile.create(tile: tile, game: @game)
    end
    redirect_to @game
  end

  def join
    @game = Game.find(params[:id])
    Playergame.create(game: @game, player_id: session[:id], score: 0)
    @game.start
    redirect_to @game
  end

  def show
    @player = Player.find(session[:id])
    @game = Game.find(params[:id])
    @playertiles = Playergame.where(player: @player, game: @game).first.gametiles
  end

  def submit
    if Verifier.new(params[:words]).valid?
      @game = Game.find(params[:id])
      @player_game = Playergame.where(game: @game, player: @game.current_player_id).first
      @player_game.take_turn(params[:words])

      @game.put_tiles_on_board_and_change_turn(params[:tiles].values, @player_game.gametiles)
      @player_game.replenish_tiles
      render :json => "true"
    else
      render :json => "false"
    end
  end

  def forfeit
    @game = Game.find(params[:id])
    @game.winner = @game.players.where.not(id: session[:id]).first
    @game.complete
    @game.save
    redirect_to root_path
  end
end

app/views/games/_game.html.erb
<div class="game_to_join">
  <div class="game_to_join_title">Game Number <%= game.id %></div>
  <div class="versus"><%= game.players.first.username.capitalize %> VS
    <% if game.players.length > 1 %>
        <%= game.players.last.username.capitalize %>
    <% else %>
        <% if game.players.first.id == session[:id] || game.players.last.id == session[:id] %>
            _______
        <% else %>
            <%= link_to "Join Game", join_game_path(game), class: "button", :method => :post %>
        <% end %>
    <% end %>
  </div>
  <div class="game_to_join_time_ago">created <%= distance_of_time_in_words_to_now(game.created_at) %> ago</div>
</div>

app/views/games/_games_to_join.html.erb
<div class="games_to_join">
  <h2 class="welcome">Open Games</h2>
  <table class="games_to_join_table">
    <tr>
    <% Game.pending.each_with_index do |game, index| %>
      <% unless game.playergames.first.player.id == session[:id] %>
        <td>
            <%= render partial: "game", locals: {game: game} %>
        </td>
      <% if index.odd? %>
        </tr>
      <% end %>
      <% end %>
    <% end %>
      </tr>
  </table>
</div>

app/views/games/_navbar.html.erb
<div id="header">
  <div class="header_title">
    <%= link_to "Scrabbulous" root_path %>
  </div>
  <div class="header_links">
    <% if session[:id] %>
      <%= link_to "logout", session_path(session[:id]), method: :delete %>
      <%= link_to "profile", games_path %>
    <% else %>
      <%= link_to "signup", new_player_path %>
      <%= link_to "signin", new_session_path %>
    <% end %>
  </div>
 </div> 

app/views/games/_tile.html.erb
<% if active %>
    <div class="tile active">
<% else %>
    <div class="tile">
<% end %>

  <div class="tile-value"><%= value %></div>
  <div class="tile-letter"><%= letter %></div>
</div>

app/views/games/index.html.erb
<% if session[:id] %>
    <% if @games %>
        <%= render partial: 'games_to_join' %>
    <% end %>
<% else %>
    <%= render partial: 'shared/welcome' %>
<% end %>

app/views/games/show.html.erb
<table id="board" data-game_id="<%= @game.id %>">
  <% Game.dimension.times do |y| %>
    <tr>
      <% Game.dimension.times do |x| %>
        <%= cell_for(x, y) %>
      <% end %>
    </tr>
  <% end %>
</table>